import { BookOpen, ClipboardCheck, GraduationCap, UserCheck } from "lucide-react";
import { DataTable } from "@/components/portal-components";
import { BarTrend, HorizontalBars, ReportFilters, ReportNavigation } from "@/components/reporting";
import { MetricCard, PageHeader, Panel } from "@/components/ui";
import { getAdminAcademicReport } from "@/lib/data/admin";

function pct(value: string): number { return Number(value.replace("%", "")) || 0; }
export default async function AcademicReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams;
  const filters = Object.fromEntries(Object.entries(raw).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value]).filter(([, value]) => typeof value === "string")) as Record<string, string>;
  const rows = await getAdminAcademicReport(filters);
  const average = (key: "attendance"|"testAverage"|"syllabus"|"recordings") => rows.length ? rows.reduce((sum,row)=>sum+pct(row[key]),0)/rows.length : 0;
  const followUp = rows.reduce((sum,row)=>sum+row.followUp,0);
  return <><PageHeader eyebrow="Reports" title="Academic performance" description="Attendance, test outcomes, content completion and students needing follow-up across active batches."/><ReportNavigation active="academic"/><ReportFilters type="academic" values={filters}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Average attendance" value={`${average("attendance").toFixed(1)}%`} detail="Finalized sessions" icon={UserCheck} tone="green"/><MetricCard label="Test average" value={`${average("testAverage").toFixed(1)}%`} detail="Released assessments" icon={ClipboardCheck} tone="blue"/><MetricCard label="Syllabus progress" value={`${average("syllabus").toFixed(1)}%`} detail="Listed batches" icon={BookOpen} tone="violet"/><MetricCard label="Needs follow-up" value={String(followUp)} detail="Academic rule flags" icon={GraduationCap} tone="amber"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel><h2 className="text-xl font-bold text-slate-950">Batch attendance comparison</h2><p className="mt-1 text-sm text-slate-500">Percent of finalized sessions attended during the selected period.</p><div className="mt-6"><BarTrend valueSuffix="%" items={rows.slice(0,6).map((row)=>({label:row.batch.split(" ")[0] || row.batch,value:pct(row.attendance),detail:`${row.students} students`}))}/></div></Panel><Panel><h2 className="text-xl font-bold text-slate-950">Learning completion</h2><p className="mt-1 text-sm text-slate-500">Weighted completion indicators.</p><div className="mt-6"><HorizontalBars items={[{label:"Syllabus released",value:Math.round(average("syllabus")),tone:"blue"},{label:"Recordings watched",value:Math.round(average("recordings")),tone:"violet"},{label:"Tests completed",value:Math.round(average("testAverage")),tone:"green"},{label:"Attendance",value:Math.round(average("attendance")),tone:"amber"}]}/></div></Panel></div><Panel className="mt-6"><h2 className="text-xl font-bold text-slate-950">Batch academic summary</h2><div className="mt-5"><DataTable actions={false} rowKey="id" rows={rows as unknown as Record<string,unknown>[]} columns={[{key:"batch",label:"Batch"},{key:"students",label:"Students"},{key:"attendance",label:"Attendance"},{key:"testAverage",label:"Test average"},{key:"syllabus",label:"Syllabus"},{key:"recordings",label:"Recording progress"},{key:"followUp",label:"Follow-up"}]}/></div></Panel></>;
}
