import { ClipboardCheck, FileText, Megaphone, PlayCircle, Plus } from "lucide-react";
import { ButtonLink, MetricCard, PageHeader, Panel, StatusBadge } from "@/components/ui";
import { getTeacherContentSummary } from "@/lib/data/teacher";
import { portalPath } from "@/lib/portal-path";

const iconByType = { recording: PlayCircle, resource: FileText, test: ClipboardCheck, announcement: Megaphone } as const;

export default async function TeacherContentPage() {
  const data = await getTeacherContentSummary();
  const batchesBase = await portalPath("/teacher/batches");
  const announcementsHref = await portalPath("/teacher/announcements");
  return <><PageHeader eyebrow="Academic content" title="Tests & Content" description="Manage recordings, resources, tests and announcements for assigned batches only." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Published recordings" value={String(data.metrics.recordings)} icon={PlayCircle} tone="blue" /><MetricCard label="Resources" value={String(data.metrics.resources)} icon={FileText} tone="violet" /><MetricCard label="Published tests" value={String(data.metrics.tests)} icon={ClipboardCheck} tone="green" /><MetricCard label="Announcements" value={String(data.metrics.announcements)} icon={Megaphone} tone="amber" /></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-950">Recent content</h2><p className="mt-1 text-sm text-slate-500">Across your assigned batches.</p></div><ButtonLink href={data.batches[0] ? `${batchesBase}/${data.batches[0].id}/recordings` : batchesBase} size="sm"><Plus className="h-4 w-4" />Add content</ButtonLink></div><div className="mt-5 divide-y divide-slate-100">{data.recent.map((item) => { const Icon = iconByType[item.type]; return <div key={item.id} className="flex items-center gap-3 py-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><Icon className="h-5 w-5" /></div><div className="flex-1"><p className="text-sm font-semibold text-slate-900">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.detail}</p></div><StatusBadge status={item.status} /></div>; })}</div></Panel><Panel><h2 className="text-xl font-bold text-slate-950">Quick access by batch</h2><div className="mt-5 space-y-3">{data.batches.map((batch) => <div key={batch.id} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold text-slate-900">{batch.course} · {batch.batch}</p><div className="mt-3 flex flex-wrap gap-2"><ButtonLink href={`${batchesBase}/${batch.id}/recordings`} variant="outline" size="sm">Recordings</ButtonLink><ButtonLink href={`${batchesBase}/${batch.id}/tests`} variant="outline" size="sm">Tests</ButtonLink><ButtonLink href={announcementsHref} variant="outline" size="sm">Announcements</ButtonLink></div></div>)}</div></Panel></div></>;
}
