<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Receipt <?php echo e($receipt->number); ?></title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1e293b; font-size: 12px; margin: 0; padding: 40px; }
        .header { border-bottom: 2px solid #1d4ed8; padding-bottom: 16px; margin-bottom: 24px; }
        .institution { font-size: 20px; font-weight: bold; color: #1d4ed8; }
        .title { text-align: right; }
        .title .label { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; }
        .title .number { font-size: 16px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        td { padding: 6px 0; vertical-align: top; }
        .row-label { width: 180px; color: #64748b; }
        .row-value { font-weight: bold; }
        .amount-box { margin-top: 24px; padding: 16px; background: #f1f5f9; border-radius: 6px; }
        .amount-box .label { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; }
        .amount-box .value { font-size: 22px; font-weight: bold; color: #0f172a; }
        .footer { margin-top: 40px; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td><span class="institution"><?php echo e($receipt->snapshot['institution'] ?? config('app.name')); ?></span></td>
            <td class="title">
                <div class="label">Payment Receipt</div>
                <div class="number"><?php echo e($receipt->number); ?></div>
            </td>
        </tr>
    </table>

    <table>
        <tr><td class="row-label">Issued</td><td class="row-value"><?php echo e($receipt->issued_at->format('d M Y, g:i A')); ?></td></tr>
        <tr><td class="row-label">Student</td><td class="row-value"><?php echo e($receipt->snapshot['student_name'] ?? 'Student'); ?></td></tr>
        <?php if(!empty($receipt->snapshot['student_code'])): ?>
        <tr><td class="row-label">Student ID</td><td class="row-value"><?php echo e($receipt->snapshot['student_code']); ?></td></tr>
        <?php endif; ?>
        <tr><td class="row-label">Course</td><td class="row-value"><?php echo e($receipt->snapshot['course_title'] ?? ''); ?></td></tr>
        <?php if(!empty($receipt->snapshot['batch_title'])): ?>
        <tr><td class="row-label">Batch</td><td class="row-value"><?php echo e($receipt->snapshot['batch_title']); ?></td></tr>
        <?php endif; ?>
        <tr><td class="row-label">Payment method</td><td class="row-value"><?php echo e($receipt->snapshot['payment_method'] ?? 'Not recorded'); ?></td></tr>
        <tr><td class="row-label">Reference</td><td class="row-value"><?php echo e($receipt->snapshot['payment_reference'] ?? ''); ?></td></tr>
        <tr><td class="row-label">Issued by</td><td class="row-value"><?php echo e($receipt->snapshot['issued_by'] ?? ''); ?></td></tr>
    </table>

    <div class="amount-box">
        <div class="label">Amount paid</div>
        <div class="value">NPR <?php echo e(number_format($receipt->amount_npr, 0)); ?></div>
    </div>

    <div class="footer">
        This receipt reflects the payment record as it stood at the time of issue and remains valid even if the
        course, price or account details are later changed. Generated by <?php echo e($receipt->snapshot['institution'] ?? config('app.name')); ?>.
    </div>
</body>
</html>
<?php /**PATH D:\AimerZone\full production versions\nepal-lms-api\resources\views/receipts/pdf.blade.php ENDPATH**/ ?>