import { CheckCircle2, Clock3, GraduationCap, UserPlus } from "lucide-react";
import { DataTable } from "@/components/portal-components";
import { BarTrend, HorizontalBars, ReportFilters, ReportNavigation } from "@/components/reporting";
import { MetricCard, PageHeader, Panel } from "@/components/ui";
import { getAdminEnrollmentReport } from "@/lib/data/admin";

export default async function EnrollmentReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams;
  const filters = Object.fromEntries(Object.entries(raw).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value]).filter(([, value]) => typeof value === "string")) as Record<string, string>;
  const rows = await getAdminEnrollmentReport(filters);
  const totals = rows.reduce((acc,row)=>({new:acc.new+row.new,approved:acc.approved+row.approved,pending:acc.pending+row.pending,free:acc.free+row.free,transfers:acc.transfers+row.transfers}),{new:0,approved:0,pending:0,free:0,transfers:0});
  return <><PageHeader eyebrow="Reports" title="Enrollment performance" description="New registrations, approved access, pending cases, free access and transfers."/><ReportNavigation active="enrollments"/><ReportFilters type="enrollment" values={filters}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="New enrollments" value={totals.new.toLocaleString()} detail="Selected period" icon={UserPlus} tone="blue"/><MetricCard label="Approved access" value={totals.approved.toLocaleString()} detail={`${totals.new?Math.round(totals.approved/totals.new*100):0}% of requests`} icon={CheckCircle2} tone="green"/><MetricCard label="Pending review" value={totals.pending.toLocaleString()} detail="Current selected periods" icon={Clock3} tone="amber"/><MetricCard label="Free enrollments" value={totals.free.toLocaleString()} detail="Approved free access" icon={GraduationCap} tone="violet"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel><h2 className="text-xl font-bold text-slate-950">Enrollment trend</h2><p className="mt-1 text-sm text-slate-500">New enrollment records by reporting period.</p><div className="mt-6"><BarTrend items={[...rows].reverse().map((row)=>({label:row.period,value:row.new,detail:`${row.approved} approved`}))}/></div></Panel><Panel><h2 className="text-xl font-bold text-slate-950">Access mix</h2><p className="mt-1 text-sm text-slate-500">Share of approved and special access.</p><div className="mt-6"><HorizontalBars items={[{label:"Approved paid",value:totals.new?Math.round(totals.approved/totals.new*100):0,tone:"green"},{label:"Pending",value:totals.new?Math.round(totals.pending/totals.new*100):0,tone:"amber"},{label:"Free",value:totals.new?Math.round(totals.free/totals.new*100):0,tone:"violet"},{label:"Transfers",value:totals.new?Math.round(totals.transfers/totals.new*100):0,tone:"blue"}]}/></div></Panel></div><Panel className="mt-6"><h2 className="text-xl font-bold text-slate-950">Enrollment period summary</h2><div className="mt-5"><DataTable actions={false} rowKey="id" rows={rows as unknown as Record<string,unknown>[]} columns={[{key:"period",label:"Period"},{key:"new",label:"New"},{key:"approved",label:"Approved"},{key:"pending",label:"Pending"},{key:"rejected",label:"Rejected"},{key:"free",label:"Free"},{key:"transfers",label:"Transfers"}]}/></div></Panel></>;
}
