import { BookOpenCheck, CheckCircle2, HeartHandshake, Smartphone, Target } from "lucide-react";
import { PublicPageHero } from "@/components/public-page";
import { ButtonLink, Panel, SectionHeading } from "@/components/ui";

export default function AboutPage() {
  return (
    <><PublicPageHero eyebrow="About Us" title="Where your dreams turn into achievements" description="Aimers Zone is a Birgunj-based learning institute committed to quality education, expert guidance and a result-oriented approach for every student." />
    <section className="bg-white py-14 sm:py-16"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-start lg:px-8"><div><p className="text-sm font-bold uppercase tracking-wider text-brand-700">Our mission</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Build strong concepts. Boost confidence. Achieve success.</h2><p className="mt-5 text-base leading-8 text-slate-600">Whether you are preparing for your Physics and Chemistry exams, an entrance test, or aiming for excellence in your coursework, Aimers Zone is built to be your complete learning partner — live classes, recordings, tests and real human support, all in one place.</p><p className="mt-4 text-base leading-8 text-slate-600">We believe strong fundamentals and genuine confidence are what turn preparation into real results. That is the idea behind everything we teach. Start with an Aim, Finish with Success.</p><ButtonLink href="/courses" className="mt-7">Explore current courses</ButtonLink></div><Panel className="bg-brand-950 text-white"><BookOpenCheck className="h-8 w-8 text-blue-200" /><h3 className="mt-5 text-2xl font-bold">Our promise</h3><p className="mt-4 text-sm leading-7 text-slate-300">Clear batch information before you pay, honest schedules, simple class joining, organized revision and real human support whenever you need it.</p><div className="mt-6 space-y-3">{["Clear pricing and schedules, no surprises", "Real teachers, not automated answers", "Support in the language you are comfortable with", "Your progress tracked honestly, every step"].map((item) => <p key={item} className="flex gap-3 text-sm text-slate-200"><CheckCircle2 className="h-5 w-5 shrink-0 text-green-400" />{item}</p>)}</div></Panel></div></section>
    <section className="bg-canvas py-14 sm:py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading title="Why students choose Aimers Zone" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Target,"Result-oriented","Every class is designed to build the concepts and confidence that lead to real results."],[Smartphone,"Mobile-first learning","Join classes, watch recordings and take tests comfortably from your phone, wherever you are."],[HeartHandshake,"Human support","Reach us directly on phone or WhatsApp whenever you have a question about your course or payment."],[BookOpenCheck,"Expert guidance","Learn from teachers who focus on clear concepts, not just covering the syllabus."]].map(([Icon,title,detail])=>{const C=Icon as typeof Target;return <Panel key={String(title)}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><C className="h-5 w-5" /></div><h3 className="mt-5 font-bold text-slate-950">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{String(detail)}</p></Panel>})}</div></div></section></>
  );
}
