import { BookOpenCheck, CheckCircle2, HeartHandshake, Smartphone, Target } from "lucide-react";
import { PublicPageHero } from "@/components/public-page";
import { ButtonLink, Panel, SectionHeading } from "@/components/ui";

export default function AboutPage() {
  return (
    <><PublicPageHero eyebrow="About" title="A focused learning platform for scheduled, supported study" description="The product is designed for one education institution serving students through live batches, recordings, tests and local support." />
    <section className="bg-white py-14 sm:py-16"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-start lg:px-8"><div><p className="text-sm font-bold uppercase tracking-wider text-brand-700">Our direction</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Make the next useful action obvious.</h2><p className="mt-5 text-base leading-8 text-slate-600">Students should not have to search through messages, links and separate folders to find the next class or missed recording. This frontend brings the batch schedule, learning content, assessments and support into one consistent experience.</p><p className="mt-4 text-base leading-8 text-slate-600">It is intentionally calmer than a generic corporate dashboard and more structured than a collection of social-media links.</p><ButtonLink href="/courses" className="mt-7">Explore current courses</ButtonLink></div><Panel className="bg-brand-950 text-white"><BookOpenCheck className="h-8 w-8 text-blue-200" /><h3 className="mt-5 text-2xl font-bold">Product promise</h3><p className="mt-4 text-sm leading-7 text-slate-300">Clear batch information before payment, honest access rules, simple class joining, organized revision and human support when automation is not enough.</p><div className="mt-6 space-y-3">{["No invented results or counters", "No hidden schedule or validity details", "No confusing duplicate enrollment action", "No unnecessary feature overload"].map((item) => <p key={item} className="flex gap-3 text-sm text-slate-200"><CheckCircle2 className="h-5 w-5 shrink-0 text-green-400" />{item}</p>)}</div></Panel></div></section>
    <section className="bg-canvas py-14 sm:py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading title="Principles guiding the experience" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Target,"Task first","Join class, continue recording and take test appear before decorative analytics."],[Smartphone,"Mobile first","Student workflows remain usable at 360 px and on modest connections."],[HeartHandshake,"Human support","Phone and WhatsApp support stay visible where students need help."],[BookOpenCheck,"Academic clarity","Course, batch, lesson, test and access language stays consistent."]].map(([Icon,title,detail])=>{const C=Icon as typeof Target;return <Panel key={String(title)}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><C className="h-5 w-5" /></div><h3 className="mt-5 font-bold text-slate-950">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{String(detail)}</p></Panel>})}</div></div></section></>
  );
}
