import { CreditCard, ReceiptText, RotateCcw, WalletCards } from "lucide-react";
import { DataTable } from "@/components/portal-components";
import { BarTrend, HorizontalBars, ReportFilters, ReportNavigation } from "@/components/reporting";
import { MetricCard, PageHeader, Panel } from "@/components/ui";
import { formatAdminNpr, getAdminFinanceReport } from "@/lib/data/admin";

export default async function FinanceReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams;
  const filters = Object.fromEntries(Object.entries(raw).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value]).filter(([, value]) => typeof value === "string")) as Record<string, string>;
  const source = await getAdminFinanceReport(filters);
  const totals = source.reduce((acc,row)=>({transactions:acc.transactions+row.transactions,gross:acc.gross+row.gross,refunds:acc.refunds+row.refunds,adjustments:acc.adjustments+row.adjustments,net:acc.net+row.net,pending:acc.pending+row.pending}),{transactions:0,gross:0,refunds:0,adjustments:0,net:0,pending:0});
  const rows = source.map((row)=>({...row,grossLabel:formatAdminNpr(row.gross),refundLabel:formatAdminNpr(row.refunds),adjustmentLabel:formatAdminNpr(row.adjustments),netLabel:formatAdminNpr(row.net)}));
  return <><PageHeader eyebrow="Reports" title="Finance oversight" description="Collections, pending proofs, refunds, adjustments and net revenue."/><ReportNavigation active="finance"/><ReportFilters type="finance" values={filters}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Net collections" value={formatAdminNpr(totals.net)} detail="Selected period" icon={WalletCards} tone="green"/><MetricCard label="Approved transactions" value={totals.transactions.toLocaleString()} detail={totals.transactions?`Average ${formatAdminNpr(Math.round(totals.net/totals.transactions))}`:"No transactions"} icon={ReceiptText} tone="blue"/><MetricCard label="Pending proofs" value={totals.pending.toLocaleString()} detail="Across daily records" icon={CreditCard} tone="amber"/><MetricCard label="Refunds and reversals" value={formatAdminNpr(totals.refunds)} detail={totals.gross?`${(totals.refunds/totals.gross*100).toFixed(2)}% of gross`:"No gross collections"} icon={RotateCcw} tone="violet"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel><h2 className="text-xl font-bold text-slate-950">Daily net collections</h2><p className="mt-1 text-sm text-slate-500">Amounts shown in thousands of Nepalese rupees.</p><div className="mt-6"><BarTrend valuePrefix="रु " items={[...source].reverse().map((row)=>({label:row.date,value:Math.round(row.net/1000),detail:`${row.transactions} txns`}))}/></div></Panel><Panel><h2 className="text-xl font-bold text-slate-950">Collection health</h2><p className="mt-1 text-sm text-slate-500">Selected-period financial composition.</p><div className="mt-6"><HorizontalBars items={[{label:"Net retained",value:totals.gross?Math.round(totals.net/totals.gross*100):0,tone:"green"},{label:"Refunds",value:totals.gross?Math.round(totals.refunds/totals.gross*100):0,tone:"violet"},{label:"Adjustments",value:totals.gross?Math.round(Math.abs(totals.adjustments)/totals.gross*100):0,tone:"blue"},{label:"Pending cases",value:Math.min(100,totals.pending),tone:"amber"}]}/></div></Panel></div><Panel className="mt-6"><h2 className="text-xl font-bold text-slate-950">Daily reconciliation summary</h2><div className="mt-5"><DataTable actions={false} rowKey="id" rows={rows as unknown as Record<string,unknown>[]} columns={[{key:"date",label:"Date"},{key:"transactions",label:"Transactions"},{key:"grossLabel",label:"Gross"},{key:"refundLabel",label:"Refunds"},{key:"adjustmentLabel",label:"Adjustments"},{key:"netLabel",label:"Net"},{key:"pending",label:"Pending proofs"}]}/></div></Panel></>;
}
