<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Idempotency keys are generated by the client, so the same string can
     * legitimately arrive from two different accounts. With the uniqueness
     * scoped only to (key, endpoint), the second caller either received the
     * first caller's stored response or overwrote their record.
     *
     * Every route carrying the `idempotent` middleware sits behind `auth`, so
     * user_id is always present in practice.
     */
    public function up(): void
    {
        Schema::table('idempotency_keys', function (Blueprint $table) {
            $table->dropUnique(['key', 'endpoint']);
            $table->unique(['key', 'endpoint', 'user_id']);
        });
    }

    public function down(): void
    {
        Schema::table('idempotency_keys', function (Blueprint $table) {
            $table->dropUnique(['key', 'endpoint', 'user_id']);
            $table->unique(['key', 'endpoint']);
        });
    }
};
