import Link from "next/link";
import { AlertCircle, ArrowRight, BookOpen, CheckCircle2, GraduationCap, UserPlus, Users, WalletCards } from "lucide-react";
import { DataTable } from "@/components/portal-components";
import { ButtonLink, MetricCard, PageHeader, Panel, StatusBadge } from "@/components/ui";
import { getSessionUser } from "@/lib/auth/server";
import { getStaffCourses, getStaffPaymentSubmissions, getStaffStudents } from "@/lib/data/staff";
import { formatNpr } from "@/lib/utils";

export default async function StaffDashboardPage() {
  const user = await getSessionUser("staff");
  const [students, payments, courses] = await Promise.all([getStaffStudents(), getStaffPaymentSubmissions(), getStaffCourses()]);
  const pending = payments.filter((item) => !["Approved", "Rejected", "Refunded"].includes(item.status)).length;
  const published = courses.filter((course) => course.published).length;
  return (
    <>
      <PageHeader eyebrow="Enrollment operations" title={`Welcome back, ${user?.name.split(" ")[0] || "Officer"}`} description="Register students, maintain courses, capture supplied payment proof and follow pending submissions without approving money." actions={<><ButtonLink href="/staff/students/new" variant="outline"><UserPlus className="h-4 w-4" />New student</ButtonLink><ButtonLink href="/staff/courses/new" variant="outline"><BookOpen className="h-4 w-4" />Add course</ButtonLink><ButtonLink href="/staff/enroll"><GraduationCap className="h-4 w-4" />Enroll student</ButtonLink></>} />
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Student records" value={String(students.length)} detail="Loaded from staff API" icon={Users} tone="blue" /><MetricCard label="Managed courses" value={String(courses.length)} detail={`${published} published`} icon={BookOpen} tone="green" /><MetricCard label="Pending review" value={String(pending)} detail="Accountant queue" icon={AlertCircle} tone="violet" /><MetricCard label="Payment submissions" value={String(payments.length)} detail="Current staff view" icon={WalletCards} tone="amber" /></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-950">Recent students</h2><p className="mt-1 text-sm text-slate-500">Profiles requiring enrollment follow-up.</p></div><Link href="/staff/students" className="flex items-center gap-1 text-sm font-bold text-brand-700">All students<ArrowRight className="h-4 w-4" /></Link></div><div className="mt-5"><DataTable rowKey="id" rows={students.slice(0, 4) as unknown as Record<string, unknown>[]} columns={[{ key: "id", label: "Student ID" }, { key: "name", label: "Student" }, { key: "course", label: "Interest / Course" }, { key: "status", label: "Status", render: (row) => <StatusBadge status={String(row.status)} /> }]} /></div></Panel><Panel><div className="flex items-center gap-3"><WalletCards className="h-6 w-6 text-brand-700" /><div><h2 className="text-xl font-bold text-slate-950">Submission queue</h2><p className="mt-1 text-sm text-slate-500">Captured by enrollment staff.</p></div></div><div className="mt-5 space-y-3">{payments.slice(0, 3).map((payment) => <Link key={payment.id} href={`/staff/payment-submissions/${payment.id}`} className="block rounded-xl border border-slate-200 p-4 hover:bg-slate-50"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-slate-950">{payment.student}</p><p className="mt-1 text-xs text-slate-500">{payment.course}</p></div><StatusBadge status={payment.status} /></div><div className="mt-3 flex items-center justify-between text-xs"><span className="text-slate-500">{payment.submitted}</span><span className="font-bold text-slate-900">{formatNpr(payment.amount)}</span></div></Link>)}</div><ButtonLink href="/staff/payment-submissions" variant="outline" className="mt-5 w-full">View all submissions</ButtonLink></Panel></div>
      <Panel className="mt-6"><div className="grid gap-5 sm:grid-cols-[auto_1fr_auto] sm:items-center"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><GraduationCap className="h-6 w-6" /></div><div><h2 className="text-lg font-bold text-slate-950">Important permission boundary</h2><p className="mt-1 text-sm leading-6 text-slate-600">Enrollment Officers may manage catalogue records and collect payment information, but cannot approve, reject, refund or change the server-resolved payable price.</p></div><ButtonLink href="/staff/courses" variant="outline">Manage courses</ButtonLink></div></Panel>
    </>
  );
}
